// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: protos/v1/card/card.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
//캐릭터 카드
type CharacterCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId         int32           `protobuf:"varint,1,opt,name=cardId,proto3" json:"cardId,omitempty"`
	Name           string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc           string          `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Sprite         string          `protobuf:"bytes,4,opt,name=sprite,proto3" json:"sprite,omitempty"`
	Atk            int32           `protobuf:"varint,5,opt,name=atk,proto3" json:"atk,omitempty"`
	Hp             int32           `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	Sd             int32           `protobuf:"varint,7,opt,name=sd,proto3" json:"sd,omitempty"`
	CharacterSkill *CharacterSkill `protobuf:"bytes,8,opt,name=characterSkill,proto3" json:"characterSkill,omitempty"`
}

func (x *CharacterCard) Reset() {
	*x = CharacterCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_card_card_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterCard) ProtoMessage() {}

func (x *CharacterCard) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_card_card_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterCard.ProtoReflect.Descriptor instead.
func (*CharacterCard) Descriptor() ([]byte, []int) {
	return file_protos_v1_card_card_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterCard) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *CharacterCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterCard) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CharacterCard) GetSprite() string {
	if x != nil {
		return x.Sprite
	}
	return ""
}

func (x *CharacterCard) GetAtk() int32 {
	if x != nil {
		return x.Atk
	}
	return 0
}

func (x *CharacterCard) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *CharacterCard) GetSd() int32 {
	if x != nil {
		return x.Sd
	}
	return 0
}

func (x *CharacterCard) GetCharacterSkill() *CharacterSkill {
	if x != nil {
		return x.CharacterSkill
	}
	return nil
}

type CharacterSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc     string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Cooldown int32  `protobuf:"varint,3,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
}

func (x *CharacterSkill) Reset() {
	*x = CharacterSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_card_card_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSkill) ProtoMessage() {}

func (x *CharacterSkill) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_card_card_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSkill.ProtoReflect.Descriptor instead.
func (*CharacterSkill) Descriptor() ([]byte, []int) {
	return file_protos_v1_card_card_proto_rawDescGZIP(), []int{1}
}

func (x *CharacterSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterSkill) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CharacterSkill) GetCooldown() int32 {
	if x != nil {
		return x.Cooldown
	}
	return 0
}

//
//장비 카드
type EquipCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EquipCard) Reset() {
	*x = EquipCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_card_card_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipCard) ProtoMessage() {}

func (x *EquipCard) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_card_card_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipCard.ProtoReflect.Descriptor instead.
func (*EquipCard) Descriptor() ([]byte, []int) {
	return file_protos_v1_card_card_proto_rawDescGZIP(), []int{2}
}

//
//스킬 카드
type SkillCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SkillCard) Reset() {
	*x = SkillCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_card_card_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkillCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillCard) ProtoMessage() {}

func (x *SkillCard) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_card_card_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillCard.ProtoReflect.Descriptor instead.
func (*SkillCard) Descriptor() ([]byte, []int) {
	return file_protos_v1_card_card_proto_rawDescGZIP(), []int{3}
}

//
//req, res
type CardId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId int32 `protobuf:"varint,1,opt,name=cardId,proto3" json:"cardId,omitempty"`
}

func (x *CardId) Reset() {
	*x = CardId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_card_card_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardId) ProtoMessage() {}

func (x *CardId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_card_card_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardId.ProtoReflect.Descriptor instead.
func (*CardId) Descriptor() ([]byte, []int) {
	return file_protos_v1_card_card_proto_rawDescGZIP(), []int{4}
}

func (x *CardId) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

type GetList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetList) Reset() {
	*x = GetList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_card_card_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetList) ProtoMessage() {}

func (x *GetList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_card_card_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetList.ProtoReflect.Descriptor instead.
func (*GetList) Descriptor() ([]byte, []int) {
	return file_protos_v1_card_card_proto_rawDescGZIP(), []int{5}
}

type CardList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterCards []*CharacterCardList `protobuf:"bytes,1,rep,name=characterCards,proto3" json:"characterCards,omitempty"`
	EquipCards     []*EquipCardList     `protobuf:"bytes,2,rep,name=equipCards,proto3" json:"equipCards,omitempty"`
	SkillCards     []*SkillCardList     `protobuf:"bytes,3,rep,name=skillCards,proto3" json:"skillCards,omitempty"`
}

func (x *CardList) Reset() {
	*x = CardList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_card_card_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardList) ProtoMessage() {}

func (x *CardList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_card_card_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardList.ProtoReflect.Descriptor instead.
func (*CardList) Descriptor() ([]byte, []int) {
	return file_protos_v1_card_card_proto_rawDescGZIP(), []int{6}
}

func (x *CardList) GetCharacterCards() []*CharacterCardList {
	if x != nil {
		return x.CharacterCards
	}
	return nil
}

func (x *CardList) GetEquipCards() []*EquipCardList {
	if x != nil {
		return x.EquipCards
	}
	return nil
}

func (x *CardList) GetSkillCards() []*SkillCardList {
	if x != nil {
		return x.SkillCards
	}
	return nil
}

type CharacterCardList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterCards []*CharacterCard `protobuf:"bytes,1,rep,name=characterCards,proto3" json:"characterCards,omitempty"`
}

func (x *CharacterCardList) Reset() {
	*x = CharacterCardList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_card_card_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterCardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterCardList) ProtoMessage() {}

func (x *CharacterCardList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_card_card_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterCardList.ProtoReflect.Descriptor instead.
func (*CharacterCardList) Descriptor() ([]byte, []int) {
	return file_protos_v1_card_card_proto_rawDescGZIP(), []int{7}
}

func (x *CharacterCardList) GetCharacterCards() []*CharacterCard {
	if x != nil {
		return x.CharacterCards
	}
	return nil
}

type EquipCardList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipCards []*EquipCard `protobuf:"bytes,1,rep,name=equipCards,proto3" json:"equipCards,omitempty"`
}

func (x *EquipCardList) Reset() {
	*x = EquipCardList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_card_card_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipCardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipCardList) ProtoMessage() {}

func (x *EquipCardList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_card_card_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipCardList.ProtoReflect.Descriptor instead.
func (*EquipCardList) Descriptor() ([]byte, []int) {
	return file_protos_v1_card_card_proto_rawDescGZIP(), []int{8}
}

func (x *EquipCardList) GetEquipCards() []*EquipCard {
	if x != nil {
		return x.EquipCards
	}
	return nil
}

type SkillCardList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillCards []*SkillCard `protobuf:"bytes,1,rep,name=skillCards,proto3" json:"skillCards,omitempty"`
}

func (x *SkillCardList) Reset() {
	*x = SkillCardList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_card_card_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkillCardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillCardList) ProtoMessage() {}

func (x *SkillCardList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_card_card_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillCardList.ProtoReflect.Descriptor instead.
func (*SkillCardList) Descriptor() ([]byte, []int) {
	return file_protos_v1_card_card_proto_rawDescGZIP(), []int{9}
}

func (x *SkillCardList) GetSkillCards() []*SkillCard {
	if x != nil {
		return x.SkillCards
	}
	return nil
}

var File_protos_v1_card_card_proto protoreflect.FileDescriptor

var file_protos_v1_card_card_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x72, 0x64,
	0x2f, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x61, 0x72,
	0x64, 0x22, 0xd7, 0x01, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x43,
	0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x70, 0x72, 0x69, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x70, 0x72, 0x69, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x74, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x74, 0x6b, 0x12, 0x0e, 0x0a,
	0x02, 0x68, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x68, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x73, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x73, 0x64, 0x12, 0x3c, 0x0a,
	0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x0e, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x22, 0x54, 0x0a, 0x0e, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6f, 0x6c, 0x64, 0x6f, 0x77,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x6f, 0x6c, 0x64, 0x6f, 0x77,
	0x6e, 0x22, 0x0b, 0x0a, 0x09, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x72, 0x64, 0x22, 0x0b,
	0x0a, 0x09, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x22, 0x20, 0x0a, 0x06, 0x43,
	0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x09, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xb5, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x72,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x63, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x43, 0x61,
	0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x33, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x43,
	0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x61, 0x72,
	0x64, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x33, 0x0a, 0x0a, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x73,
	0x22, 0x50, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x43, 0x61, 0x72,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x63, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x43, 0x61, 0x72,
	0x64, 0x73, 0x22, 0x40, 0x0a, 0x0d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x72, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x43,
	0x61, 0x72, 0x64, 0x73, 0x22, 0x40, 0x0a, 0x0d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x72,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x61, 0x72, 0x64,
	0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0a, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x43, 0x61, 0x72, 0x64, 0x73, 0x32, 0xf9, 0x02, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12,
	0x35, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x43,
	0x61, 0x72, 0x64, 0x12, 0x0c, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49,
	0x64, 0x1a, 0x13, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x12, 0x2d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0c, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x61,
	0x72, 0x64, 0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x43, 0x61, 0x72, 0x64, 0x12, 0x2d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0c, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x3e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0d, 0x2e, 0x63,
	0x61, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x61,
	0x72, 0x64, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x43, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0d, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x0d, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x0d, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_v1_card_card_proto_rawDescOnce sync.Once
	file_protos_v1_card_card_proto_rawDescData = file_protos_v1_card_card_proto_rawDesc
)

func file_protos_v1_card_card_proto_rawDescGZIP() []byte {
	file_protos_v1_card_card_proto_rawDescOnce.Do(func() {
		file_protos_v1_card_card_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_v1_card_card_proto_rawDescData)
	})
	return file_protos_v1_card_card_proto_rawDescData
}

var file_protos_v1_card_card_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protos_v1_card_card_proto_goTypes = []interface{}{
	(*CharacterCard)(nil),     // 0: card.CharacterCard
	(*CharacterSkill)(nil),    // 1: card.CharacterSkill
	(*EquipCard)(nil),         // 2: card.EquipCard
	(*SkillCard)(nil),         // 3: card.SkillCard
	(*CardId)(nil),            // 4: card.CardId
	(*GetList)(nil),           // 5: card.GetList
	(*CardList)(nil),          // 6: card.CardList
	(*CharacterCardList)(nil), // 7: card.CharacterCardList
	(*EquipCardList)(nil),     // 8: card.EquipCardList
	(*SkillCardList)(nil),     // 9: card.SkillCardList
}
var file_protos_v1_card_card_proto_depIdxs = []int32{
	1,  // 0: card.CharacterCard.characterSkill:type_name -> card.CharacterSkill
	7,  // 1: card.CardList.characterCards:type_name -> card.CharacterCardList
	8,  // 2: card.CardList.equipCards:type_name -> card.EquipCardList
	9,  // 3: card.CardList.skillCards:type_name -> card.SkillCardList
	0,  // 4: card.CharacterCardList.characterCards:type_name -> card.CharacterCard
	2,  // 5: card.EquipCardList.equipCards:type_name -> card.EquipCard
	3,  // 6: card.SkillCardList.skillCards:type_name -> card.SkillCard
	4,  // 7: card.Card.GetCharacterCard:input_type -> card.CardId
	4,  // 8: card.Card.GetEquipCard:input_type -> card.CardId
	4,  // 9: card.Card.GetSkillCard:input_type -> card.CardId
	5,  // 10: card.Card.GetCharacterCardList:input_type -> card.GetList
	5,  // 11: card.Card.GetEquipCardList:input_type -> card.GetList
	5,  // 12: card.Card.GetSkillCardList:input_type -> card.GetList
	5,  // 13: card.Card.GetCardList:input_type -> card.GetList
	0,  // 14: card.Card.GetCharacterCard:output_type -> card.CharacterCard
	2,  // 15: card.Card.GetEquipCard:output_type -> card.EquipCard
	3,  // 16: card.Card.GetSkillCard:output_type -> card.SkillCard
	7,  // 17: card.Card.GetCharacterCardList:output_type -> card.CharacterCardList
	8,  // 18: card.Card.GetEquipCardList:output_type -> card.EquipCardList
	9,  // 19: card.Card.GetSkillCardList:output_type -> card.SkillCardList
	6,  // 20: card.Card.GetCardList:output_type -> card.CardList
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protos_v1_card_card_proto_init() }
func file_protos_v1_card_card_proto_init() {
	if File_protos_v1_card_card_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_v1_card_card_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_card_card_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_card_card_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_card_card_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkillCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_card_card_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_card_card_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_card_card_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_card_card_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterCardList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_card_card_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipCardList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_v1_card_card_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkillCardList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_v1_card_card_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_v1_card_card_proto_goTypes,
		DependencyIndexes: file_protos_v1_card_card_proto_depIdxs,
		MessageInfos:      file_protos_v1_card_card_proto_msgTypes,
	}.Build()
	File_protos_v1_card_card_proto = out.File
	file_protos_v1_card_card_proto_rawDesc = nil
	file_protos_v1_card_card_proto_goTypes = nil
	file_protos_v1_card_card_proto_depIdxs = nil
}
