apiVersion: v1
kind: Namespace
metadata:
  name: card-dungeon
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: card-dungeon
  namespace: card-dungeon
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: card-dungeon.myroom.dev
      http:
        paths:
          - path: /cards
            pathType: Prefix
            backend:
              service:
                name: portfolio
                port:
                  number: 10503
  tls:
    - hosts:
        - card-dungeon.myroom.dev
      secretName: card-dungeon
---
apiVersion: v1
kind: Service
metadata:
  name: card
  namespace: card-dungeon
  labels:
    app: card
spec:
  selector:
    app: card
  ports:
    - port: 10503
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: card
  namespace: card-dungeon
  labels:
    app: card
spec:
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
        - name: card
          image: gmae199boy/server-card:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10503
